# Configuration script to Travis-CI
language: python
python:
  - "3.7"
install:
  - pip install -e .[test]
  - pip install coveralls
script:
  - pytest --cov=compman --cov-report=term tests
after_success:
  coveralls
