name: openvario-compman

on:
  push:
    branches: master
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv coveralls
        pipenv install --dev
    - name: Test with pytest
      run: |
        pipenv run pytest -v --junit-xml var/test-results/results.xml --cov-report=term --cov=compman  tests
    - name: Check with mypy
      run: |
        pipenv run mypy src tests
    - name: Check with black
      run: |
        pipenv run black --check setup.py src tests
    - name: Check with isort
      run: |
        pipenv run isort --check-only setup.py src tests
    - name: Coveralls
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
        COVERALLS_PARALLEL: true
      run: |
        coveralls --service=github

  report:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Coveralls Finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
      run: |
        pip install coveralls
        coveralls --service=github --finish
